config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  scope :api do
  	resources :category_produits
  	resources :commandes
  	resources :ligne_commandes
  	resources :produits
  	resources :category_produits

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category_produit.rb
class CategoryProduit < ApplicationRecord
  has_many :produits
end

app/controllers/category_produits_controller.rb
class CategoryProduitsController < ApplicationController
  before_action :set_category_produit, only: [:show, :edit, :update, :destroy]

  # GET /category_produits
  # GET /category_produits.json
  def index
    @category_produits = CategoryProduit.all
  end

  # GET /category_produits/1
  # GET /category_produits/1.json
  def show
  end

  # GET /category_produits/new
  def new
    @category_produit = CategoryProduit.new
  end

  # GET /category_produits/1/edit
  def edit
  end

  # POST /category_produits
  # POST /category_produits.json
  def create
    @category_produit = CategoryProduit.new(category_produit_params)

    respond_to do |format|
      if @category_produit.save
        format.html { redirect_to @category_produit, notice: 'Category produit was successfully created.' }
        format.json { render :show, status: :created, location: @category_produit }
      else
        format.html { render :new }
        format.json { render json: @category_produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_produits/1
  # PATCH/PUT /category_produits/1.json
  def update
    respond_to do |format|
      if @category_produit.update(category_produit_params)
        format.html { redirect_to @category_produit, notice: 'Category produit was successfully updated.' }
        format.json { render :show, status: :ok, location: @category_produit }
      else
        format.html { render :edit }
        format.json { render json: @category_produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_produits/1
  # DELETE /category_produits/1.json
  def destroy
    @category_produit.destroy
    respond_to do |format|
      format.html { redirect_to category_produits_url, notice: 'Category produit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_produit
      @category_produit = CategoryProduit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_produit_params
      params.fetch(:category_produit, {})
    end
end

app/helpers/category_produits_helper.rb
module CategoryProduitsHelper
end

app/views/category_produits/_form.html.erb
<%= form_with(model: category_produit, local: true) do |form| %>
  <% if category_produit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category_produit.errors.count, "error") %> prohibited this category_produit from being saved:</h2>

      <ul>
      <% category_produit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/category_produits/edit.html.erb
<h1>Editing Category Produit</h1>

<%= render 'form', category_produit: @category_produit %>

<%= link_to 'Show', @category_produit %> |
<%= link_to 'Back', category_produits_path %>

app/views/category_produits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Category Produits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category_produits.each do |category_produit| %>
      <tr>
        <td><%= link_to 'Show', category_produit %></td>
        <td><%= link_to 'Edit', edit_category_produit_path(category_produit) %></td>
        <td><%= link_to 'Destroy', category_produit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category Produit', new_category_produit_path %>

app/views/category_produits/new.html.erb
<h1>New Category Produit</h1>

<%= render 'form', category_produit: @category_produit %>

<%= link_to 'Back', category_produits_path %>

app/views/category_produits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_produit_path(@category_produit) %> |
<%= link_to 'Back', category_produits_path %>